services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    volumes:
      - miniodata:/var/lib/minio/data

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgredb
      POSTGRES_PASSWORD: postgredb
      POSTGRES_DB: kma-training-support
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  miniodata:
