# file này để khởi chạy các dịch vụ phụ trợ
# Cần lệnh docker-compose up -d -> tạo container cho Postgres + MinIO, cấu hình đúng port, user/pass, volume dể backend kết nối ngay và dùng
# Các image này được lấy từ Docker hub chính thức
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - miniodata:/var/lib/minio/data

  db:
    # dùng image sẵn trên Docker Hub
    image: postgres:16
    restart: always
    # tạo user, password, database mặc định
    environment:
      POSTGRES_USER: postgredb
      POSTGRES_PASSWORD: postgredb
      POSTGRES_DB: kma-training-support
    # mở port 5432 ra ngoài để có thể connect từ máy host
    ports:
      - '5432:5432'
    #  gắn một thư mục (volume) để lưu dữ liệu ra ngoài container -> khi container xóa thì dữ liệu vẫn còn
    volumes:
      - pgdata:/var/lib/postgresql/

volumes:
  pgdata:
  miniodata:

  # khi có nhiều service trong cùng một docker-compose.yml, chúng nằm chung trong một mạng nội bộ cho Docker quản lý

  # tóm lại file này dùng để tạo môi trường các thứ cho postgres, minio
  # việc còn lại là phải tự tạo cấu trúc như table, dữ liệu ...
